# Generated by Django 5.2.3 on 2025-06-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=155,
                        primary_key=True,
                        serialize=False,
                        editable=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField()),
                ("contract_name", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("position_latitude", models.FloatField()),
                ("position_longitude", models.FloatField()),
                ("banking", models.BooleanField(default=False)),
                ("bonus", models.BooleanField(default=False)),
                ("status", models.CharField(max_length=50)),
                ("last_update", models.DateTimeField()),
                ("connected", models.BooleanField(default=True)),
                ("overflow", models.BooleanField(default=False)),
                ("total_capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("main_capacity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "overflow_capacity",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "ordering": ["contract_name", "number"],
                "indexes": [
                    models.Index(
                        fields=["contract_name", "number"],
                        name="app_station_contrac_8c683f_idx",
                    )
                ],
                "unique_together": {("contract_name", "number")},
            },
        ),
    ]
