# Generated by Django 5.2.3 on 2025-06-25 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("commercial_name", models.CharField(max_length=255)),
                ("country_code", models.CharField(max_length=10)),
                ("cities", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="station",
            options={"ordering": ["contract", "number"]},
        ),
        migrations.RemoveIndex(
            model_name="station",
            name="app_station_contrac_8c683f_idx",
        ),
        migrations.AlterUniqueTogether(
            name="station",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="station",
            name="contract",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stations",
                to="app.contract",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="station",
            unique_together={("contract", "number")},
        ),
        migrations.AddIndex(
            model_name="station",
            index=models.Index(
                fields=["contract", "number"],
                name="app_station_contrac_53cd1b_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="station",
            name="contract_name",
        ),
    ]
