# Generated by Django 5.2.3 on 2025-06-25 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_contract_alter_station_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
            options={
                "verbose_name_plural": "positions",
            },
        ),
        migrations.CreateModel(
            name="Stands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bikes", models.IntegerField()),
                ("stands", models.IntegerField()),
                ("mechanical_bikes", models.IntegerField()),
                ("electrical_bikes", models.IntegerField()),
                ("electrical_internal_battery_bikes", models.IntegerField()),
                ("electrical_removable_battery_bikes", models.IntegerField()),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="station",
            name="main_capacity",
        ),
        migrations.RemoveField(
            model_name="station",
            name="overflow_capacity",
        ),
        migrations.RemoveField(
            model_name="station",
            name="position_latitude",
        ),
        migrations.RemoveField(
            model_name="station",
            name="position_longitude",
        ),
        migrations.RemoveField(
            model_name="station",
            name="total_capacity",
        ),
        migrations.AddField(
            model_name="station",
            name="position",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="station",
                to="app.position",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="main_stands",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_station",
                to="app.stands",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="overflow_stands",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="overflow_station",
                to="app.stands",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="total_stands",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="total_station",
                to="app.stands",
            ),
        ),
    ]
