# Generated by Django 5.2.3 on 2025-06-30 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_contract_alter_station_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="station",
            name="main_capacity",
        ),
        migrations.RemoveField(
            model_name="station",
            name="overflow_capacity",
        ),
        migrations.RemoveField(
            model_name="station",
            name="total_capacity",
        ),
        migrations.CreateModel(
            name="Park",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=155,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=50)),
                ("position_latitude", models.FloatField()),
                ("position_longitude", models.FloatField()),
                ("access_type", models.CharField(max_length=50)),
                ("locker_type", models.CharField(max_length=50)),
                ("has_surveillance", models.BooleanField()),
                ("is_free", models.BooleanField()),
                ("address", models.CharField(max_length=255)),
                ("zip_code", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=100)),
                ("is_off_street", models.BooleanField()),
                ("has_electric_support", models.BooleanField()),
                ("has_physical_reception", models.BooleanField()),
                (
                    "contract",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parks",
                        to="app.contract",
                    ),
                ),
            ],
            options={
                "ordering": ["contract", "number"],
                "indexes": [
                    models.Index(
                        fields=["contract", "number"],
                        name="app_park_contrac_3b7c1f_idx",
                    )
                ],
                "unique_together": {("contract", "number")},
            },
        ),
        migrations.CreateModel(
            name="Stand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("total", "Total"),
                            ("main", "Main"),
                            ("overflow", "Overflow"),
                        ],
                        max_length=8,
                    ),
                ),
                ("bikes", models.PositiveIntegerField()),
                ("stands", models.PositiveIntegerField()),
                ("mechanical_bikes", models.PositiveIntegerField()),
                ("electrical_bikes", models.PositiveIntegerField()),
                (
                    "electrical_internal_battery_bikes",
                    models.PositiveIntegerField(),
                ),
                (
                    "electrical_removable_battery_bikes",
                    models.PositiveIntegerField(),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stands",
                        to="app.station",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["station", "kind"],
                        name="app_stand_station_906384_idx",
                    )
                ],
                "unique_together": {("station", "kind")},
            },
        ),
    ]
